### ISSUE TITLE
Legacy Fuel

### ISSUE THREAD

**Issue by iSentrie** [GMA950/esx_advancedgarage#1]
It gives random value of fuel every time I bring the car.

**Comment by iSentrie** [comment]
Oh, looks like fuel table missing. :)
`[ERROR] [MySQL] [esx_advancedgarage] An error happens on MySQL for query "UPDATE owned_vehicles SET `fuel` = 49.459999084472656 WHERE plate = 'BAV 733'": ER_BAD_FIELD_ERROR: Unknown column 'fuel' in 'field list'`

**Comment by iSentrie** [comment]
Made a pull for sql file.

**Comment by GMA950** [comment]
I added it myself, thank you
